object frmBackgroundDialog: TfrmBackgroundDialog
  Left = 0
  Top = 0
  Align = alClient
  AlphaBlend = True
  AlphaBlendValue = 120
  BorderStyle = bsNone
  Caption = 'frmBackgroundDialog'
  ClientHeight = 240
  ClientWidth = 461
  Color = clBlack
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  WindowState = wsMaximized
  PixelsPerInch = 96
  TextHeight = 13
end
